-- SQLBook: Code

-- SQLBook: Code
-- Endpoint: /lm/doctor/licenses
-- Listado de LM emitida por un médico
select
	id_lic ,
	operador,
	ccaf ,
	entidad_pagadora,
	folio ,
	fecha_emision ,
	empleador_adscrito,
	codigo_interno_prestador,
	comuna_prestador,
	fecha_ultimo_estado,
	ultimo_estado,
	rut_trabajador ,
	sexo_trabajador,
	edad_trabajador,
	tipo_reposo,
	dias_reposo,
	fecha_inicio_reposo,
	comuna_reposo,
	tipo_licencia,
	rut_medico,
	especialidad_profesional ,
	tipo_profesional,
	tipo_licencia_pronunciamiento,
	codigo_continuacion_pronunciamiento,
	dias_autorizados_pronunciamiento,
	codigo_diagnostico_pronunciamiento,
	codigo_autorizacion_pronunciamiento,
	causa_rechazo_pronunciamiento ,
	tipo_reposo_pronunciamiento,
	derecho_a_subsidio_pronunciamiento,
	rut_empleador,
	calidad_trabajador ,
	actividad_laboral_trabajador,
	ocupacion,
	entidad_pagadora_zona_c,
	fecha_recepcion_empleador,
	regimen_previsional,
	entidad_pagadora_subsidio,
	comuna_laboral,
	comuna_uso_compin,
	cantidad_de_pronunciamientos,
	cantidad_de_zonas_d,
	secuencia_estados ,
	cod_diagnostico_principal,
	cod_diagnostico_secundario,
	periodo ,
	propensity_score_rn,
	propensity_score_rn2,
	propensity_score_frecuencia_mensual,
	propensity_score_frecuencia_semanal,
	propensity_score_otorgados_mensual,
	propensity_score_otorgados_semanal,
	propensity_score_ml,
	propensity_score
from
	lme.df_propensity_score
where
	 folio = :folio;
